var religiaUla = ["Wymień sposoby poznawania świata.", "Dlaczego ciało jest ważnym Bożym darem i w jaki sposób przez nie poznajesz świat?", "Czy są jakieś dziedziny, których poznawanie jest dla ciebie fascynujące?", "W jaki sposób możesz bardziej poznać siebie?", "Co to znaczy, że każdy człowiek ma swoją godność?", "Omów główne wydarzenia historii zbawienia (Stary Testament, od stworzenia świata poprzez grzech pierworodny, potop, Babel, niewolę egipską, wyjście z Egiptu).", "Opowiedz historię króla Dawida i króla Salomona.", "Kim są prorocy? Omów historię życia wybranego proroka ST", "Co to znaczy, że Izrael jest narodem wybranym?", "Czym była niewola babilońska?", "Omów historię i okoliczności przyjścia na świat Jezusa Chrystusa.", "Podaj przykłady proroctw o Mesjaszu ze Starego Testamentu.", "Co to znaczy że jesteś odkupiona?", "Źródła historyczne (pozabiblijne) mówiące o Jezusie.", "Omów życie, działalność i nauczanie Jezusa Chrystusa. Co oznacza słowo Ewangelia?", "Rola Maryi w dziele zbawienia", "Czym są sakramenty? Jakie znasz sakramenty?", "Omów poszczególne sakramenty. Kiedy możemy je przyjąć? Jak się należy przygotować? Jakie jest ich znaczenie? Jaki jest ich przebieg? Kto je sprawuje? Jakich symboli używamy?", "Co oznacza, że Kościół jest Mistycznym Ciałem Jezusa?", "Jak została ustanowiona Eucharystia?", "Jakie są części Mszy Świętej? Co dzieje się podczas Mszy Świętej?", "Jak przygotowujesz się do przyjęcia Pana Jezusa w Komunii Świętej?", "Jak należy się zachować przed i po przyjęciu Pana Jezusa?", "Czym jest Adoracja Najświętszego Sakramentu?", "Czym są symbole wiary: Credo i Skład Apostolski?", "Omów ważne momenty z historii Kościoła: renesans, Sobór Trydencki, protestantyzm, ekumenizm.", "Jak Kościół współpracuje ze społeczeństwem, jaką rolę pełnił wcześniej, w czym udziela się dzisiaj?", "Na jakie okresy dzieli się rok liturgiczny?", "Co oznaczają poszczególne kolory?", "Jakie są najważniejsze święta i uroczystości w ciągu roku? Co w sposób szczególny przeżywamy w danym miesiącu/okresie? (np. październik miesiącem różańcowym, itd.)", "Opowiedz o swoim patronie/ulubionym świętym.", "Opowiedz o św. Józefie.", "Kim był bł. Stefan Wyszyński?", "Kim była bł. matka Elżbieta Róża Czacka?", "W czym możemy ich naśladować?"]
var religiaBasia = ["Jak Pan Bóg do nas mówi?", "Kiedy podczas Mszy św. czytamy Słowo Boże?", "W jaki sposób powinniśmy słuchać Słowa Bożego? Jak je wprowadzać w życie?", "Kiedy Ty czytasz Słowo Boże?", "Jak Jezus przedstawiony jest w Piśmie Świętym?", "Przyjaźń z Jezusem umacnia się poprzez udział w Eucharystii - jak to rozumiesz?", "Co to jest przyjaźń?", "Jak możesz umacniać przyjaźń z Jezusem?", "Jak Przyjaciel Jezus(a?) traktuje innych ludzi?", "Jak została ustanowiona Eucharystia?", "Jakie są części Mszy Świętej? Co dzieje się podczas Mszy Świętej?", "Jak należy się zachować przed i po przyjęciu Pana Jezusa?", "Czym jest Adoracja Najświętszego Sakramentu?", "Co to jest wdzięczność?", "Za co najbardziej dziękujesz Panu Bogu? Pamiętasz o modlitwie dziękczynienia?", "Za co możesz byc wdzięczny innym ludziom?", "Kiedy i w jakich okolicznościach odmawiamy modlitwę dziękczynną?", "Jak dobrze przeżyć Sakrament Pokuty, o czym warto pamiętać?", "Jakie są konsekwencje grzechu?", "Grzeszymy złymi czynami, ale jak jeszcze?", "Opowiedz przypowieść, która przypomina, że Bóg zawsze jest gotowy nam przebaczyć. Jak my powinniśmy przebaczać innym?", "O co możesz prosić Jezusa?", "W którym momencie Mszy św. wypowiadamy modlitwę prośby?", "Co to jest modlitwa uwielbienia? Jak możesz wielbić Boga?", "Na jakie okresy dzieli się rok liturgiczny?", "Co oznaczają poszczególne kolory?", "Jakie są najważniejsze święta i uroczystości w ciągu roku? Co w sposób szczególny przeżywamy w danym miesiącu/okresie? (np. październik miesiącem różańcowym, itd.)", "Opowiedz o swoim patronie/ulubionym świętym.", "Opowiedz o św. Józefie.", "Kim był bł. Stefan Wyszyński?", "Kim była bł. matka Elżbieta Róża Czacka?", "W czym możemy ich naśladować?"]
function wyswietlReligiaUla()
{
	$('#tabelaReligiaUla').append('<tr><th>zagadnienia</th><th>zaliczone</th></tr>');
	for (let i = 0; i < religiaUla.length; i++) 
	{
		$('#tabelaReligiaUla').append('<tr><td>' + religiaUla[i] + '</td><td></td></tr>');
	}
}
function wyswietlReligiaBasia()
{
	$('#tabelaReligiaBasia').append('<tr><th>zagadnienia</th><th>zaliczone</th></tr>');
	for (let i = 0; i < religiaBasia.length; i++) 
	{
		$('#tabelaReligiaBasia').append('<tr><td>' + religiaBasia[i] + '</td><td></td></tr>');
	}
}